- name: set prompt
  ansible.builtin.shell: set-prompt "{{ app_name }}-{{ env }}"

- name: disable default redis
  ansible.builtin.shell: dnf module disable redis -y

- name: enable redis
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: update listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: update protection
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: start redis
  ansible.builtin.systemd_service:
    enabled: yes
    state: restarted

