- name: set prompt
  ansible.builtin.shell: set-prompt "{{ app_name }}-{{ env }}"

- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start myql server
  ansible.builtin.systemd_service:
    name: mysql
    enabled: yes
    state: restarted

- name: setuo mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass Roboshop@1
