- name: set-prompt
  ansible.builtin.shell: set-prompt "{{ app_name }}-{{ env }}"

- name: install golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: include app_prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prerequisites.yml

- name: download dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup.yml


