- name: set prompt
  ansible.builtin.shell: set-prompt "{{ app_name }}-{{ env }}"

- name: include nodejs role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yml

- name: copy repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: load master data
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.devopsb78.online </app/db/master-data.js

- name: restart catalogue
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted




