- name: set prompt
  ansible.builtin.shell: set-prompt "{{ app_name }}-{{ env }}"

- name: include nodejs role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yml

- name: copy mongodb repo
  ansible.builtin.templates:
    src: {{ app_name }}.repo
    dest: /etc/yum.repos.d/{{ app_name }}.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: load master data
  ansible.builtin.shell: mongosh --host mongodb.devopsb78.online </app/db/master-data.js

- name: restart catalogue
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted




