- name: copying service file
  ansible.builtin.template:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: start application service
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    daemon-reload: yes
    enabled: yes
    state: restarted